/* Backrooms level expansion: clean menu, six new task-driven levels, hostile/neutral/peaceful classes, PC+mobile interaction parity. */
(function(){
'use strict';
const LEVELS=[
 {id:'0',name:'Level 0 — The Yellow Rooms',class:'HOSTILE',desc:'Endless yellow corridors. Something is listening.'},
 {id:'1',name:'Level 1 — Habitable Zone',class:'NEUTRAL',desc:'Concrete service halls. Supplies are useful, but nothing feels safe.'},
 {id:'2',name:'Level 37 — Poolrooms',class:'PEACEFUL',desc:'Warm tile, still water, and a silence that feels too perfect.'},
 {id:'x6',name:'Level 6 — Terror Hotel',class:'HOSTILE',desc:'A decaying hotel. Restore power and find the service elevator.'},
 {id:'x14',name:'Level 14 — Flooded Offices',class:'HOSTILE',desc:'Abandoned offices under rising water. Find the emergency override.'},
 {id:'x9',name:'Level 9 — Service Tunnels',class:'NEUTRAL',desc:'Industrial tunnels. Route power through three substations.'},
 {id:'x21',name:'Level 21 — Endless Archive',class:'NEUTRAL',desc:'A silent library where the lights never reach the stacks.'},
 {id:'x3999',name:'Level 3999 — Quiet Garden',class:'PEACEFUL',desc:'An impossible indoor garden. Find the maintenance gate home.'},
 {id:'x37b',name:'Level 37B — Deep Pools',class:'PEACEFUL',desc:'Deeper water, blue service lights, and no visible exit.'}
];
const meta=Object.fromEntries(LEVELS.map(x=>[x.id,x]));
let selected='0', active=null, customGroup=null, customBoxes=[], taskMeshes=[], taskState=[], baseVisibility=[];
let taskUI=null, lastPos=null, lastT=0;
function css(){if(document.getElementById('level-expansion-style'))return;const s=document.createElement('style');s.id='level-expansion-style';s.textContent=`#level-select{background:#090909;color:#eee;border-color:#8e7d55}#level-select optgroup{font-weight:bold;color:#d6b86a}#level-expansion-panel{position:absolute;top:18px;left:50%;transform:translateX(-50%);z-index:55;display:none;width:min(520px,92vw);padding:11px 14px;background:rgba(8,8,8,.78);border:1px solid rgba(255,255,255,.18);border-radius:7px;color:#eee;backdrop-filter:blur(5px);text-shadow:1px 1px 2px #000}.lex-title{font-weight:bold;letter-spacing:1.5px;font-size:13px}.lex-desc{font-size:11px;opacity:.72;margin-top:3px}.lex-task{margin-top:7px;font-size:12px}.lex-progress{height:4px;background:#222;margin-top:6px;overflow:hidden}.lex-fill{height:100%;width:0;background:#d6b86a;transition:width .25s}.lex-tag{float:right;font-size:10px;letter-spacing:1px;opacity:.75}.lex-complete{opacity:.45;text-decoration:line-through}.lex-crosshair{position:absolute;left:50%;top:50%;width:5px;height:5px;margin:-2px;border-radius:50%;background:rgba(255,255,255,.7);z-index:19;pointer-events:none}#level-select option{background:#101010;color:#eee}`;document.head.appendChild(s)}
function cleanMenu(){const sel=document.getElementById('level-select');if(!sel)return;sel.innerHTML='';[['HOSTILE','Hostile — danger is expected'],['NEUTRAL','Neutral — exploration and survival'],['PEACEFUL','Peaceful — atmosphere and discovery']].forEach(([group,label])=>{const og=document.createElement('optgroup');og.label=label;LEVELS.filter(x=>x.class===group).forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name;og.appendChild(o)});sel.appendChild(og)});sel.value='0';sel.addEventListener('change',()=>{selected=sel.value;updateMenuInfo()});
 const info=document.getElementById('room-info');if(info&&!document.getElementById('level-menu-info')){const d=document.createElement('div');d.id='level-menu-info';d.style.cssText='font-size:11px;color:#aaa;line-height:1.4;margin-top:2px';info.parentNode.insertBefore(d,info.nextSibling)}updateMenuInfo()}
function updateMenuInfo(){const d=document.getElementById('level-menu-info');const m=meta[selected];if(d&&m)d.innerHTML=`<b style="color:#d6b86a">${m.class}</b> · ${m.desc}`}
function makeMat(c,r=.8,m=0){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}
function box(x,y,z,w,h,d,mat,collide=true){const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);q.position.set(x,y+h/2,z);customGroup.add(q);if(collide)customBoxes.push(new THREE.Box3(new THREE.Vector3(x-w/2,y,z-d/2),new THREE.Vector3(x+w/2,y+h,z+d/2)));return q}
function cyl(x,y,z,r,h,mat){const q=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,16),mat);q.position.set(x,y+h/2,z);customGroup.add(q);return q}
function floor(size,mat){const q=new THREE.Mesh(new THREE.PlaneGeometry(size,size),mat);q.rotation.x=-Math.PI/2;q.position.y=0;customGroup.add(q)}
function light(x,y,z,c,int=1,dist=24){const l=new THREE.PointLight(c,int,dist);l.position.set(x,y,z);customGroup.add(l)}
function label(text,x,y,z){const c=document.createElement('canvas');c.width=512;c.height=128;const k=c.getContext('2d');k.fillStyle='rgba(0,0,0,.62)';k.fillRect(8,20,496,88);k.fillStyle='#eee';k.font='bold 34px Arial';k.textAlign='center';k.fillText(text,256,76);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.scale.set(3.1,.7,1);s.position.set(x,y,z);customGroup.add(s)}
function task(name,x,z,color,action){const m=makeMat(color,.45,.15);const q=new THREE.Mesh(new THREE.BoxGeometry(1.0,1.15,.38),m);q.position.set(x,.75,z);q.userData.task=true;q.userData.action=action;q.userData.name=name;q.userData.done=false;customGroup.add(q);taskMeshes.push(q);return q}
function setupUI(){if(taskUI)return;taskUI=document.createElement('div');taskUI.id='level-expansion-panel';taskUI.innerHTML='<div class="lex-title"><span id="lex-name"></span><span id="lex-tag" class="lex-tag"></span></div><div id="lex-desc" class="lex-desc"></div><div id="lex-tasks"></div>';document.body.appendChild(taskUI);const c=document.createElement('div');c.className='lex-crosshair';document.body.appendChild(c)}
function showUI(){setupUI();taskUI.style.display='block';updateTasks()}
function updateTasks(){if(!taskUI||!active)return;document.getElementById('lex-name').textContent=active.meta.name;document.getElementById('lex-tag').textContent=active.meta.class;document.getElementById('lex-desc').textContent=active.meta.desc;const list=document.getElementById('lex-tasks');list.innerHTML='';let done=0;active.tasks.forEach((t,i)=>{if(taskState[i])done++;const d=document.createElement('div');d.className='lex-task'+(taskState[i]?' lex-complete':'');d.textContent=(taskState[i]?'✓ ':'□ ')+t;list.appendChild(d)});const p=document.createElement('div');p.className='lex-progress';p.innerHTML='<div class="lex-fill"></div>';p.querySelector('.lex-fill').style.width=(done/active.tasks.length*100)+'%';list.appendChild(p)}
function hideUI(){if(taskUI)taskUI.style.display='none'}
function hideBase(){if(typeof scene==='undefined')return;baseVisibility=[];for(const o of scene.children){if(o===camera||o===controls.getObject()||o===customGroup)continue;if(o.name==='LOCAL_PLAYER_AVATAR'||o.userData&&o.userData.remotePlayer)continue;baseVisibility.push([o,o.visible]);o.visible=false}}
function restoreBase(){for(const [o,v] of baseVisibility)o.visible=v;baseVisibility=[]}
function clearCustom(){if(customGroup){scene.remove(customGroup);customGroup.traverse(o=>{if(o.geometry)o.geometry.dispose&&o.geometry.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose&&m.dispose());else o.material.dispose&&o.material.dispose()}})}customGroup=null;customBoxes=[];taskMeshes=[];taskState=[];active=null;hideUI()}
function build(id){clearCustom();restoreBase();selected=id;const m=meta[id];if(!m||id==='0'||id==='1'||id==='2')return false;customGroup=new THREE.Group();customGroup.name='EXPANSION_LEVEL';scene.add(customGroup);hideBase();const dark=makeMat(0x171717,1),concrete=makeMat(0x565656,.96),white=makeMat(0xc8d0cc,.72),tile=makeMat(0x7f8d8c,.78),grass=makeMat(0x263a2b,1),wood=makeMat(0x3b3027,.92),rust=makeMat(0x51352a,.98,.1),blue=makeMat(0x3d6f78,.7,.05);floor(180,m.class==='PEACEFUL'?(id==='x3999'?grass:tile):concrete);
 if(id==='x6') hotel(concrete,wood,rust); else if(id==='x14') offices(concrete,white,blue); else if(id==='x9') tunnels(concrete,rust); else if(id==='x21') archive(wood,white); else if(id==='x3999') garden(grass,white); else deepPools(tile,white,blue);
 active={meta:m,tasks:taskList(id)};taskState=active.tasks.map(()=>false);showUI();lastPos=null;return true}
function taskList(id){return id==='x6'?['Find the maintenance key','Restore power at the breaker','Reach the service elevator']:id==='x14'?['Find the emergency pump','Open the floodgate','Use the red override panel']:id==='x9'?['Activate substation A','Activate substation B','Activate substation C','Open the main security door']:id==='x21'?['Find the missing archive key','Locate the marked shelf','Unlock the staff exit']:id==='x3999'?['Find the garden maintenance key','Follow the irrigation line','Open the maintenance gate']:['Find the blue access token','Activate the deep-pool pumps','Reach the submerged service door']}
function addTaskSequence(points,colors){points.forEach((p,i)=>task(activeName(points,i),p[0],p[1],colors[i%colors.length],i)}
function activeName(){return ''}
function hotel(c,w,r){for(let z=-50;z<=50;z+=20){box(-22,0,z,2,4.5,16,w);box(22,0,z,2,4.5,16,w);box(0,0,z-8,42,4.5,1.2,w);box(0,0,z+8,42,4.5,1.2,w);light(0,4.5,z,0xffd98a,.8,22)}for(let x=-15;x<=15;x+=10)for(let z=-38;z<=38;z+=16){box(x,.1,z,5,.25,3,w,false)}const pts=[[-12,-28], [14,4], [-6,36]];pts.forEach((p,i)=>task(['Maintenance key','Breaker','Service elevator'][i],p[0],p[1],i===1?0xd6b86a:0x8a5f3b));label('HOTEL SERVICE FLOOR',0,5,0)}
function offices(c,w,b){for(let x=-48;x<=48;x+=16){box(x,0,-30,1,4,60,c);box(x,0,30,1,4,60,c)}for(let z=-20;z<=20;z+=20){box(-30,0,z,36,3.5,1,w);box(30,0,z,36,3.5,1,w)}for(let x=-40;x<=40;x+=20)light(x,4.7,0,0x8fd0d5,.5,20);[[ -38,-22],[0,18],[38,-10]].forEach((p,i)=>task(['Emergency pump','Floodgate','Red override'][i],p[0],p[1],b.color||0x4b7f87));label('FLOOD RESPONSE WING',0,5,0)}
function tunnels(c,r){for(let z=-55;z<=55;z+=14){box(-12,0,z,1.3,4,12,c);box(12,0,z,1.3,4,12,c);box(0,4,z,25,.7,12,r);light(0,4.1,z,0xb9c8b9,.35,15)}[[0,-38],[-7,0],[7,38],[0,55]].forEach((p,i)=>task(['SUB A','SUB B','SUB C','SECURITY DOOR'][i],p[0],p[1],0x8b8f87));label('UTILITY TUNNEL C',0,4.8,-55)}
function archive(w,c){for(let x=-40;x<=40;x+=10)for(let z=-40;z<=40;z+=14){if(Math.abs(x)<6&&Math.abs(z)<8)continue;box(x,0,z,3.5,3.2,11,w,false);box(x,0,z-5,3.5,3.2,.5,c,false)}for(let x=-35;x<=35;x+=14)light(x,4.6,0,0xf2dfb0,.25,18);[[-32,-30],[22,-2],[-18,34]].forEach((p,i)=>task(['Archive key','Marked shelf','Staff exit'][i],p[0],p[1],0xa98a55));label('ARCHIVE — NO PUBLIC ACCESS',0,5,0)}
function garden(g,w){for(let x=-45;x<=45;x+=15){for(let z=-45;z<=45;z+=15){if(Math.random()<.72)cyl(x,0,z,1.2,2.5,g)}light(0,6,0,0xb6ffd0,.9,45);for(let a=0;a<12;a++){const ang=a*Math.PI/6;box(Math.cos(ang)*24,.05,Math.sin(ang)*24,.8,.2,5,w,false)}[[-28,-18],[18,8],[0,35]].forEach((p,i)=>task(['Garden key','Irrigation line','Maintenance gate'][i],p[0],p[1],0x83a98b));label('QUIET GARDEN',0,6,0)}
function deepPools(t,w,b){floor(150,t);for(let x=-45;x<=45;x+=15){for(let z=-45;z<=45;z+=15){box(x,0,z,12,.35,12,t,false)}}for(let x=-45;x<=45;x+=15)light(x,4.6,0,0x7fbfd0,.55,18);[[-30,-30],[24,0],[0,34]].forEach((p,i)=>task(['Blue access token','Pool pumps','Service door'][i],p[0],p[1],i===2?0x6f9ba4:0x80c4d0));label('DEEP POOLS — LOWER LEVEL',0,5,0)}
function nearestTask(){if(!customGroup||!controls)return null;const p=controls.getObject().position;let best=null,bd=3.2;for(const q of taskMeshes){if(q.userData.done)continue;const d=q.position.distanceTo(p);if(d<bd){bd=d;best=q}}return best}
function interact(){if(!active)return;const q=nearestTask();if(!q)return;if(q.userData.done)return;q.userData.done=true;const i=taskMeshes.indexOf(q);if(i>=0)taskState[i]=true;updateTasks();if(typeof showToast==='function')showToast(q.userData.name+' COMPLETE',1100);if(taskState.every(Boolean)){if(typeof showToast==='function')showToast('OBJECTIVE COMPLETE — FIND THE EXIT',2500);active.complete=true;}}
function collision(){if(!customGroup||!controls)return;const p=controls.getObject().position;for(const b of customBoxes){const q=p.clone();q.y=1.6;if(b.containsPoint(q)){if(lastPos)p.copy(lastPos);break}}lastPos=p.clone()}
function updateAtmosphere(){if(!active||!customGroup||!controls)return;const p=controls.getObject().position;const moving=lastPos&&p.distanceTo(lastPos)>.015;const now=performance.now();if(moving&&now-lastT>900){lastT=now;try{const a=new AudioContext();const o=a.createOscillator(),g=a.createGain();o.frequency.value=active.meta.class==='HOSTILE'?58:92;g.gain.value=.008;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.035);setTimeout(()=>a.close(),80)}catch(e){}}}
function loop(){if(active){collision();updateAtmosphere()}requestAnimationFrame(loop)}
function bindAction(){document.addEventListener('keydown',e=>{if(e.code==='KeyE')interact()},{capture:true});const b=document.getElementById('mobile-action');if(b)b.addEventListener('click',e=>{if(active){e.preventDefault();e.stopImmediatePropagation();interact()}},{capture:true});}
function boot(){css();cleanMenu();setupUI();bindAction();const sel=document.getElementById('level-select');const poll=setInterval(()=>{if(typeof gameActive!=='undefined'&&gameActive&&selected&&selected!=='0'&&selected!=='1'&&selected!=='2'){if(!active||active.meta.id!==selected)build(selected)}if(typeof gameActive!=='undefined'&&!gameActive&&active){clearCustom();} },250);loop()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
