/* Backrooms Remastered UI system — clean layout, guidebook, expedition shell, PC/mobile parity. */
(function(){
  'use strict';
  const KEY='backrooms_remastered_expedition_v1';
  const q=id=>document.getElementById(id);
  const safe=fn=>{try{return fn();}catch(e){return undefined;}};
  const defaults={name:'EXPEDITION 0047',level:'0',survivors:1,lore:0,deaths:0,keys:0,secrets:0,endings:[],startedAt:Date.now()};
  let data=load(); let guideOpen=false;
  function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){return {...defaults};}}
  function persist(){safe(()=>localStorage.setItem(KEY,JSON.stringify(data)));}
  function css(){
    if(q('br-ui-style'))return;
    const s=document.createElement('style');s.id='br-ui-style';s.textContent=`
      :root{--br-gold:#d8b84e;--br-line:rgba(255,255,255,.12);--br-good:#78f0c7}
      #start-screen.br-clean{display:flex!important;align-items:center;justify-content:center;padding:24px;background:radial-gradient(circle at 50% 38%,rgba(148,119,31,.18),rgba(0,0,0,.98) 68%),linear-gradient(180deg,#070808,#020303)}
      #br-menu{width:min(1040px,94vw);height:min(700px,88vh);display:grid;grid-template-columns:245px 1fr;overflow:hidden;border:1px solid var(--br-line);background:rgba(5,6,6,.86);box-shadow:0 30px 120px rgba(0,0,0,.78);backdrop-filter:blur(10px);font-family:'Courier New',monospace;text-align:left;color:#eee}
      #br-menu-side{padding:28px 18px;border-right:1px solid var(--br-line);display:flex;flex-direction:column;background:linear-gradient(180deg,rgba(255,216,92,.03),transparent)}
      #br-menu-brand{font-size:28px;letter-spacing:3px;line-height:.95;color:#f4e6ab;text-shadow:0 0 18px rgba(255,212,70,.2)}#br-menu-brand small{display:block;margin-top:9px;font-size:9px;letter-spacing:3px;color:#6d6d6d}
      #br-nav{margin-top:34px;display:grid;gap:5px}.br-nav{appearance:none;width:100%!important;padding:12px 14px!important;border:1px solid transparent!important;background:transparent!important;color:#aaa!important;text-align:left!important;font:700 11px 'Courier New',monospace!important;letter-spacing:2px!important;box-shadow:none!important;border-radius:2px!important;cursor:pointer!important}.br-nav:hover,.br-nav.active{border-color:rgba(216,184,78,.26)!important;background:rgba(216,184,78,.08)!important;color:#f7e7a4!important}.br-side-note{margin-top:auto;color:#5e5e5e;font-size:9px;line-height:1.6;letter-spacing:1px}
      #br-menu-main{min-width:0;display:flex;flex-direction:column;padding:30px 34px;overflow:auto}.br-view{display:none;flex:1;min-width:0}.br-view.active{display:block}.br-kicker{color:var(--br-gold);font-size:9px;letter-spacing:3px}.br-view h2{margin:8px 0 6px;font-size:28px;letter-spacing:2px;color:#f8f0cc}.br-view p{margin:0;color:#858585;line-height:1.6;font-size:12px}
      .br-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:12px;margin-top:22px}.br-card{border:1px solid var(--br-line);background:rgba(255,255,255,.025);padding:16px}.br-card h3{margin:0 0 9px;font-size:11px;letter-spacing:2px;color:#d9d0ad}.br-row{display:flex;gap:8px;flex-wrap:wrap}.br-row>*{flex:1;min-width:130px}
      #br-menu select,#br-menu input{width:100%!important;background:#0d0f0f!important;border:1px solid var(--br-line)!important;color:#eee!important;border-radius:3px!important;padding:11px 12px!important;font-size:12px!important}#br-menu button.br-action{width:auto!important;min-width:150px!important;padding:11px 14px!important;border-radius:3px!important;font-size:11px!important;letter-spacing:1px!important;border:1px solid rgba(216,184,78,.5)!important;background:#d8b84e!important;color:#050505!important;box-shadow:none!important}#br-menu button.br-action.alt{background:#0d0f0f!important;color:#ddd!important;border-color:var(--br-line)!important}
      .br-statgrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.br-stat{padding:12px;border:1px solid var(--br-line);background:rgba(0,0,0,.18)}.br-stat b{display:block;color:#f0e5bd;font-size:19px}.br-stat span{color:#666;font-size:9px;letter-spacing:1px}.br-timeline{margin-top:12px;border-left:1px solid rgba(216,184,78,.3);padding-left:15px}.br-step{position:relative;padding:8px 0 14px;color:#aaa;font-size:11px}.br-step:before{content:'';position:absolute;left:-20px;top:11px;width:7px;height:7px;border:1px solid var(--br-gold);border-radius:50%;background:#050606}.br-step b{color:#eee}.br-step small{display:block;color:#626262;margin-top:3px}
      #br-guide{position:fixed;inset:0;z-index:1500;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.82);backdrop-filter:blur(8px);font-family:'Courier New',monospace;color:#eee}.br-guide-card{width:min(1020px,94vw);height:min(690px,88vh);display:grid;grid-template-columns:205px 1fr;overflow:hidden;border:1px solid var(--br-line);background:#0a0c0c}.br-guide-nav{padding:18px;border-right:1px solid var(--br-line);overflow:auto}.br-guide-nav button{display:block;width:100%!important;text-align:left!important;background:transparent!important;color:#888!important;border:1px solid transparent!important;font:700 10px 'Courier New',monospace!important;padding:10px!important;letter-spacing:1px!important}.br-guide-nav button.active{color:#eee!important;border-color:rgba(216,184,78,.25)!important;background:rgba(216,184,78,.07)!important}.br-guide-main{padding:24px 28px;overflow:auto}.br-guide-main h2{margin:0 0 7px;color:#efe4ba;letter-spacing:2px}.br-guide-main p{color:#929292;line-height:1.7;font-size:12px}.br-guide-entry{padding:14px 0;border-top:1px solid var(--br-line)}.br-guide-entry b{color:#ded6bb}.br-guide-entry code{display:inline-block;padding:3px 6px;border:1px solid rgba(216,184,78,.25);color:var(--br-gold);background:rgba(216,184,78,.05)}
      #br-hud-shell{position:fixed;inset:0;z-index:29;pointer-events:none;display:none;font-family:'Courier New',monospace;color:#eee}.br-hud-panel{position:absolute;border:1px solid rgba(255,255,255,.11);background:rgba(0,0,0,.42);backdrop-filter:blur(5px);padding:9px 11px;box-shadow:0 8px 30px rgba(0,0,0,.14)}#br-hud-top{left:14px;top:14px;width:min(330px,46vw)}#br-hud-title{font-size:11px;letter-spacing:2px;color:#e9e0bd}#br-hud-objective{margin-top:3px;color:#898989;font-size:10px;line-height:1.5}.br-hud-mini{font-size:9px;color:#676767;letter-spacing:1px}.br-meter{height:4px;background:rgba(255,255,255,.11);margin-top:5px;overflow:hidden}.br-meter i{display:block;width:100%;height:100%;background:var(--br-gold);transition:width .15s}#br-hud-right{right:14px;top:14px;text-align:right}#br-hud-voice{color:#8f8f8f;font-size:9px;letter-spacing:1px}#br-hud-voice.live{color:var(--br-good)}#br-hud-bottom{left:14px;bottom:14px;min-width:230px}.br-hud-line{display:flex;justify-content:space-between;gap:15px;font-size:9px;color:#7d7d7d}.br-hud-line strong{color:#eee}.br-hotkeys{margin-top:7px;font-size:8px;color:#575757;letter-spacing:.6px}
      #br-mobile-extra{display:none;position:fixed;right:12px;bottom:195px;z-index:50;gap:8px;flex-direction:column;pointer-events:auto}.br-mx{width:58px;height:58px;border-radius:50%;border:1px solid rgba(255,255,255,.3);background:rgba(0,0,0,.48);color:#fff;font:700 9px 'Courier New',monospace}.br-mx:active{background:rgba(216,184,78,.3)}
      @media(max-width:760px){#br-menu{height:90vh;grid-template-columns:88px 1fr}#br-menu-side{padding:18px 8px}#br-menu-brand{font-size:12px;letter-spacing:2px}.br-nav{padding:10px 7px!important;font-size:8px!important;letter-spacing:1px!important;text-align:center!important}.br-view h2{font-size:22px}.br-grid{grid-template-columns:1fr}.br-statgrid{grid-template-columns:repeat(2,1fr)}#br-menu-main{padding:22px 16px}.br-guide-card{grid-template-columns:95px 1fr}.br-guide-main{padding:20px 16px}#br-mobile-extra{display:flex}#br-hud-top{width:220px;left:9px;top:9px}.br-hotkeys{display:none}}
    `;document.head.appendChild(s);
  }
  function switchTab(tab){document.querySelectorAll('.br-nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.br-view').forEach(v=>v.classList.toggle('active',v.dataset.view===tab));if(tab==='profile')refreshProfile();}
  function refreshProfile(){const p=safe(()=>window.BackroomsProfile?.get())||{};if(q('br-p-name'))q('br-p-name').textContent=String(p.name||'PLAYER').toUpperCase();if(q('br-p-tag'))q('br-p-tag').textContent=String(p.tag||'SURVIVOR').toUpperCase();const dot=q('br-profile-preview')?.firstElementChild;if(dot){dot.style.background=p.outfit||'#4e7bd9';dot.style.borderColor=p.accent||'#d8b84e';}}
  function refresh(){const level=String(typeof currentLevel!=='undefined'?currentLevel:(q('level-select')?.value||data.level||'0'));data.level=level;persist();['br-s-level','br-e-level'].forEach(id=>{if(q(id))q(id).textContent='LEVEL '+level;});if(q('br-s-survivors'))q('br-s-survivors').textContent=data.survivors||1;if(q('br-s-lore'))q('br-s-lore').textContent=data.lore||0;if(q('br-s-deaths'))q('br-s-deaths').textContent=data.deaths||0;if(q('br-e-lore'))q('br-e-lore').textContent=data.lore||0;if(q('br-e-keys'))q('br-e-keys').textContent=data.keys||0;if(q('br-e-secrets'))q('br-e-secrets').textContent=data.secrets||0;if(q('br-exp-title'))q('br-exp-title').textContent=data.name;refreshProfile();}

  function menuDom(){
    const start=q('start-screen');if(!start||q('br-menu'))return;start.classList.add('br-clean');[...start.children].forEach(n=>n.style.display='none');
    const wrap=document.createElement('div');wrap.id='br-menu';wrap.innerHTML=`
      <aside id="br-menu-side"><div id="br-menu-brand">THE<br>BACKROOMS<small>REMASTERED</small></div><nav id="br-nav"><button class="br-nav active" data-tab="play">PLAY</button><button class="br-nav" data-tab="expedition">EXPEDITION</button><button class="br-nav" data-tab="profile">PROFILE</button><button class="br-nav" data-tab="guide">GUIDE BOOK</button><button class="br-nav" data-tab="settings">SETTINGS</button></nav><div class="br-side-note">Build 01<br>Explore. Survive.<br>Uncover the truth.</div></aside>
      <main id="br-menu-main">
        <section class="br-view active" data-view="play"><div class="br-kicker">BACKROOMS // START</div><h2>Choose your run.</h2><p>Solo and co-op use the same puzzle logic; solo routes have alternate clues and guidebook hints.</p><div class="br-grid"><div class="br-card"><h3>LEVEL</h3><select id="br-level"><option value="0">LEVEL 0 — THE YELLOW ROOMS</option><option value="1">LEVEL 1 — HABITABLE ZONE</option><option value="2">LEVEL 37 — THE POOLROOMS</option></select><div style="height:8px"></div><div class="br-row"><button class="br-action" id="br-solo">PLAY SOLO</button><button class="br-action alt" id="br-create">CREATE ROOM</button></div><div style="height:8px"></div><div class="br-row"><input id="br-room" maxlength="12" placeholder="ROOM CODE"><button class="br-action alt" id="br-join">JOIN ROOM</button></div></div><div class="br-card"><h3>EXPEDITION</h3><div class="br-statgrid"><div class="br-stat"><b id="br-s-level">LEVEL 0</b><span>CURRENT</span></div><div class="br-stat"><b id="br-s-survivors">1</b><span>SURVIVORS</span></div><div class="br-stat"><b id="br-s-lore">0</b><span>LORE</span></div><div class="br-stat"><b id="br-s-deaths">0</b><span>DEATHS</span></div></div><div style="height:10px"></div><button class="br-action alt" id="br-continue">CONTINUE EXPEDITION</button></div></div><div class="br-card" style="margin-top:12px"><h3>CAMPAIGN ROUTE</h3><div class="br-timeline"><div class="br-step"><b>LEVEL 0</b> — Find the exit<small>Learn the rooms. Find supplies. Survive the first signal.</small></div><div class="br-step"><b>LEVEL 1</b> — Secure supplies<small>Storage, keys and the first generator objective.</small></div><div class="br-step"><b>LEVEL 2</b> — Generator puzzle<small>Solo: environmental clue route. Co-op: split information route.</small></div><div class="br-step"><b>LEVEL 3</b> — Escape the entity<small>Noise, light and route choice start to matter.</small></div><div class="br-step"><b>LEVEL 37</b> — Poolrooms<small>Secret route available. Deep pools can lead elsewhere.</small></div></div></div></section>
        <section class="br-view" data-view="expedition"><div class="br-kicker">PERSISTENT RUN</div><h2 id="br-exp-title">EXPEDITION 0047</h2><p>Progress is stored locally in this browser so the same expedition can be resumed.</p><div class="br-statgrid"><div class="br-stat"><b id="br-e-level">LEVEL 0</b><span>POSITION</span></div><div class="br-stat"><b id="br-e-lore">0</b><span>LORE FRAGMENTS</span></div><div class="br-stat"><b id="br-e-keys">0</b><span>KEYS</span></div><div class="br-stat"><b id="br-e-secrets">0</b><span>SECRETS</span></div></div><div class="br-card" style="margin-top:12px"><h3>RUN STATE</h3><p>Continue from your last saved browser state, or start a fresh expedition code.</p><div style="height:10px"></div><div class="br-row"><button class="br-action" id="br-new-exp">NEW EXPEDITION</button><button class="br-action alt" id="br-guide-open">OPEN GUIDE BOOK</button></div></div></section>
        <section class="br-view" data-view="profile"><div class="br-kicker">PLAYER IDENTITY</div><h2>Your profile.</h2><p>Customize your name, role and colors. The existing profile editor stays synchronized with this screen.</p><div class="br-card" style="margin-top:22px"><h3>IDENTITY PREVIEW</h3><div id="br-profile-preview" style="display:flex;align-items:center;gap:12px;padding:14px 0"><div style="width:54px;height:54px;border-radius:50%;background:#4e7bd9;border:3px solid #d8b84e"></div><div><b id="br-p-name">PLAYER</b><div id="br-p-tag" style="color:#888;font-size:10px;letter-spacing:2px;margin-top:4px">SURVIVOR</div></div></div><button class="br-action" id="br-profile-open">OPEN PROFILE</button></div></section>
        <section class="br-view" data-view="guide"><div class="br-kicker">FIELD MANUAL</div><h2>Guide Book</h2><p>Every co-op puzzle gets a solo-safe fallback: extra clue, timed sequence, slower timer, or alternate route.</p><div class="br-grid"><div class="br-card"><h3>SOLO RULE</h3><p>Never hard-lock a lone player behind a puzzle that assumes another human exists.</p><div style="height:10px"></div><button class="br-action" id="br-open-guide-2">OPEN GUIDE</button></div><div class="br-card"><h3>QUICK CONTROLS</h3><p>PC and mobile expose the same actions. J opens the guide; mobile gets dedicated GUIDE / ITEMS / LIGHT / CROUCH / VOICE buttons.</p></div></div></section>
        <section class="br-view" data-view="settings"><div class="br-kicker">SYSTEM</div><h2>Settings</h2><p>Keep the interface readable on desktop and phones without flattening the horror atmosphere.</p><div class="br-card" style="margin-top:22px"><h3>ACCESSIBILITY</h3><div class="br-row"><button class="br-action alt" id="br-motion">TOGGLE REDUCED MOTION</button><button class="br-action alt" id="br-close-menu">CLOSE MENU</button></div></div></section>
      </main>`;
    start.appendChild(wrap);
    wrap.querySelectorAll('.br-nav').forEach(btn=>btn.onclick=()=>switchTab(btn.dataset.tab));
    q('br-solo').onclick=()=>q('solo-btn')?.click();q('br-create').onclick=()=>q('host-btn')?.click();q('br-join').onclick=()=>{const x=q('room-code'),y=q('br-room');if(x&&y)x.value=y.value;q('join-btn')?.click();};q('br-continue').onclick=()=>q('solo-btn')?.click();q('br-guide-open').onclick=q('br-open-guide-2').onclick=()=>openGuide();q('br-profile-open').onclick=()=>q('profile-btn')?.click();
    q('br-new-exp').onclick=()=>{data={...defaults,name:'EXPEDITION '+String(Math.floor(Math.random()*9000)+1000),startedAt:Date.now()};persist();refresh();};q('br-close-menu').onclick=()=>{if(typeof gameActive!=='undefined'&&gameActive)start.style.display='none';};q('br-motion').onclick=()=>{document.documentElement.classList.toggle('br-reduced');};refresh();
  }

  const pages={
    basics:{title:'Survive the first five minutes.',body:`<div class="br-guide-entry"><b>MOVE QUIETLY</b><p>Sprinting drains stamina and makes you easier to notice. Noise is a gameplay resource.</p></div><div class="br-guide-entry"><b>CHECK THE ENVIRONMENT</b><p>Some objects are useful; some are deliberately fake. Watch lights, writing, stains, props and geometry.</p></div><div class="br-guide-entry"><b>SOLO SAFE</b><p><code>SOLO ROUTE</code> never requires another player to exist.</p></div>`},
    entities:{title:'Entities learn your habits.',body:`<div class="br-guide-entry"><b>SMILER</b><p>Darkness is its advantage. Bright light is a warning.</p></div><div class="br-guide-entry"><b>HOUND</b><p>Footsteps, sprinting and voice activity can attract it.</p></div><div class="br-guide-entry"><b>WATCHER</b><p>Some encounters reward observation instead of chasing.</p></div>`},
    items:{title:'Carry only what matters.',body:`<div class="br-guide-entry"><b>CORE KIT</b><p>Flashlight • batteries • almond water • medkit • key • fuse • radio • map • camera • detector • glow stick • noise maker.</p></div><div class="br-guide-entry"><b>LIMITED INVENTORY</b><p>Team storage can hold surplus supplies, while personal pockets stay limited.</p></div>`},
    puzzles:{title:'Puzzles should be fair, not frustrating.',body:`<div class="br-guide-entry"><b>CO-OP</b><p>Player A may see <code>RED 4</code> and Player B <code>BLUE 7</code>. Voice communication completes the shared solution.</p></div><div class="br-guide-entry"><b>SOLO FALLBACK</b><p>The same puzzle can reveal a second clue, replace simultaneous switches with a timed sequence, or open a slower route.</p></div>`},
    levels:{title:'The campaign is a journey.',body:`<div class="br-guide-entry"><b>0 → 1</b><p>Find the exit and learn the changing rooms.</p></div><div class="br-guide-entry"><b>1 → 2 → 3 → 5</b><p>Supplies, generator puzzle, entity escape and the first major transition.</p></div><div class="br-guide-entry"><b>6 → 9 → 37 → 37B</b><p>Hotel, lights-out survival, suburbs and poolrooms. Secret routes stay hidden from the normal selector.</p></div>`},
    endings:{title:'Your ending records what you did.',body:`<div class="br-guide-entry"><b>NORMAL ESCAPE</b><p>Reach an exit without triggering deeper checks.</p></div><div class="br-guide-entry"><b>TEAM ESCAPE</b><p>Everybody survives.</p></div><div class="br-guide-entry"><b>ABANDONED / LOST / ENTITY</b><p>Failures become story outcomes instead of instant forgettable resets.</p></div><div class="br-guide-entry"><b>SECRET / TRUE ESCAPE</b><p>Collect lore and discover hidden routes.</p></div>`},
    secrets:{title:'Not everything belongs in the selector.',body:`<div class="br-guide-entry"><b>THE BACKROOMS REMEMBERS</b><p>Rooms may subtly change, familiar props may move, and one player can witness an event another never sees.</p></div><div class="br-guide-entry"><b>PLAYER ECHOES</b><p>UNKNOWN nameplates, silhouettes and familiar avatars in the wrong place may be clues — or traps.</p></div>`}
  };
  function guideDom(){if(q('br-guide'))return;const g=document.createElement('div');g.id='br-guide';g.innerHTML=`<div class="br-guide-card"><aside class="br-guide-nav"><button class="active" data-page="basics">BASICS</button><button data-page="entities">ENTITIES</button><button data-page="items">ITEMS</button><button data-page="puzzles">PUZZLES</button><button data-page="levels">LEVELS</button><button data-page="endings">ENDINGS</button><button data-page="secrets">SECRETS</button></aside><section class="br-guide-main"><div id="br-guide-content"></div><div style="margin-top:18px"><button id="br-guide-close" class="br-action alt" style="width:auto!important">CLOSE</button></div></section></div>`;document.body.appendChild(g);g.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>renderGuide(b.dataset.page));q('br-guide-close').onclick=closeGuide;renderGuide('basics');}
  function renderGuide(page){const p=pages[page]||pages.basics;q('br-guide-content').innerHTML=`<div class="br-kicker">FIELD MANUAL</div><h2>${p.title}</h2>${p.body}`;q('br-guide').querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));}
  function openGuide(){guideDom();q('br-guide').style.display='flex';guideOpen=true;}function closeGuide(){if(q('br-guide'))q('br-guide').style.display='none';guideOpen=false;}

  function hud(){if(q('br-hud-shell'))return;const h=document.createElement('div');h.id='br-hud-shell';h.innerHTML=`<div id="br-hud-top" class="br-hud-panel"><div id="br-hud-title">LEVEL 0 // THE YELLOW ROOMS</div><div id="br-hud-objective">Find a way deeper.</div><div class="br-hud-mini" style="margin-top:7px">STAMINA</div><div class="br-meter"><i id="br-hud-stamina"></i></div></div><div id="br-hud-right" class="br-hud-panel"><div id="br-hud-voice">VOICE OFF • CAPSLOCK PTT</div><div class="br-hud-mini" style="margin-top:5px">EXPEDITION <span id="br-hud-exp">0047</span></div></div><div id="br-hud-bottom" class="br-hud-panel"><div class="br-hud-line"><span>NOISE</span><strong id="br-hud-noise">QUIET</strong></div><div class="br-hud-line" style="margin-top:4px"><span>INVENTORY</span><strong id="br-hud-inv">0 / 8</strong></div><div class="br-hotkeys">J GUIDE • B EMOTE • E INTERACT • C CROUCH • G DROP</div></div>`;document.body.appendChild(h);}
  function mobileParity(){if(q('br-mobile-extra'))return;const m=document.createElement('div');m.id='br-mobile-extra';m.innerHTML='<button class="br-mx" data-a="guide">GUIDE</button><button class="br-mx" data-a="inventory">ITEMS</button><button class="br-mx" data-a="flashlight">LIGHT</button><button class="br-mx" data-a="crouch">CROUCH</button><button class="br-mx" data-a="voice">VOICE</button>';document.body.appendChild(m);m.querySelectorAll('[data-a]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.a);}));}
  function action(a){if(a==='guide'){openGuide();return;}if(a==='voice'){window.BackroomsVoice?.toggleMute?.();return;}if(a==='flashlight'){document.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyF',key:'f',bubbles:true}));return;}if(a==='crouch'){document.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyC',key:'c',bubbles:true}));return;}if(a==='inventory'){safe(()=>showToast?.('INVENTORY • E PICK UP • G DROP',1400));}}
  function bind(){document.addEventListener('keydown',e=>{if(e.code==='KeyJ'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();openGuide();}if(e.code==='Escape'&&guideOpen)closeGuide();});const level=q('level-select'),br=q('br-level');if(level&&br){br.value=level.value;br.onchange=()=>{level.value=br.value;level.dispatchEvent(new Event('change',{bubbles:true}));};}const solo=q('solo-btn');if(solo)solo.addEventListener('click',()=>{data.survivors=1;data.level=String(q('level-select')?.value||data.level);persist();refresh();},true);}
  function runtime(){const active=typeof gameActive!=='undefined'&&gameActive;if(q('br-hud-shell'))q('br-hud-shell').style.display=active?'block':'none';const level=String(typeof currentLevel!=='undefined'?currentLevel:data.level||'0');const names={'0':'LEVEL 0 // THE YELLOW ROOMS','1':'LEVEL 1 // HABITABLE ZONE','2':'LEVEL 37 // THE POOLROOMS'};if(q('br-hud-title'))q('br-hud-title').textContent=names[level]||('LEVEL '+level);if(q('br-hud-exp'))q('br-hud-exp').textContent=String(data.name||'EXPEDITION 0047').replace('EXPEDITION ','');const v=safe(()=>window.BackroomsVoice?.state());if(q('br-hud-voice')){q('br-hud-voice').textContent=v?.enabled?(v.muted?'VOICE MUTED':'VOICE LIVE • CAPSLOCK PTT'):'VOICE OFF • CAPSLOCK PTT';q('br-hud-voice').classList.toggle('live',!!v?.enabled&&!v?.muted);}const st=safe(()=>typeof stamina!=='undefined'?stamina:null);if(q('br-hud-stamina')&&st!==null)q('br-hud-stamina').style.width=Math.max(0,Math.min(100,st))+'%';const inv=safe(()=>typeof inventory!=='undefined'&&Array.isArray(inventory)?inventory.length:0);if(q('br-hud-inv'))q('br-hud-inv').textContent=(inv||0)+' / 8';const sprint=typeof isSprinting!=='undefined'&&isSprinting;if(q('br-hud-noise'))q('br-hud-noise').textContent=sprint?'LOUD':'QUIET';requestAnimationFrame(runtime);}
  function init(){css();menuDom();guideDom();hud();mobileParity();bind();refresh();runtime();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  window.BackroomsUI={openGuide,closeGuide,refresh,expedition:()=>({...data}),action};
})();
