/* Backrooms Remastered voice chat — opt-in WebRTC, proximity audio, wall attenuation and radio mode. */
(function(){
'use strict';
const V={stream:null,enabled:false,muted:true,ptt:true,pressed:false,radio:false,audio:new Map(),wired:new WeakSet(),lastError:''};
const q=id=>document.getElementById(id),safe=fn=>{try{return fn();}catch(e){}};
function css(){if(q('voice-style'))return;const s=document.createElement('style');s.id='voice-style';s.textContent=`#voice-panel{position:fixed;right:18px;top:18px;z-index:80;display:none;gap:7px;align-items:center;padding:8px 10px;border:1px solid rgba(255,255,255,.16);border-radius:8px;background:rgba(0,0,0,.62);backdrop-filter:blur(7px);font:10px 'Courier New',monospace;letter-spacing:1px;color:#ddd}#voice-panel button{width:auto!important;padding:7px 9px!important;font:700 10px 'Courier New',monospace;letter-spacing:1px}#voice-dot{width:8px;height:8px;border-radius:50%;background:#666}#voice-dot.live{background:#5dffbf;box-shadow:0 0 10px rgba(93,255,191,.7)}#voice-dot.talk{background:#ffcf59;box-shadow:0 0 12px rgba(255,207,89,.75)}#voice-status{min-width:92px}@media(max-width:650px){#voice-panel{right:10px;top:10px;padding:6px 7px}#voice-panel button{font-size:9px!important;padding:6px 8px!important}}`;document.head.appendChild(s);}
function dom(){if(q('voice-panel'))return;const p=document.createElement('div');p.id='voice-panel';p.innerHTML='<span id="voice-dot"></span><span id="voice-status">VOICE OFF</span><button id="voice-enable" type="button">MIC</button><button id="voice-mute" type="button" class="secondary">MUTE</button><button id="voice-radio" type="button" class="secondary">RADIO</button>';document.body.appendChild(p);q('voice-enable').onclick=enable;q('voice-mute').onclick=toggleMute;q('voice-radio').onclick=toggleRadio;}
function ui(show=true){const p=q('voice-panel');if(p)p.style.display=show?'flex':'none';refresh();}
function refresh(){const st=q('voice-status'),dot=q('voice-dot'),m=q('voice-mute'),r=q('voice-radio');if(!st)return;if(!V.stream){st.textContent='VOICE OFF';dot.className='';m.textContent='MUTE';r.textContent='RADIO';return;}const tx=V.enabled&&!V.muted&&(!V.ptt||V.pressed);st.textContent=V.muted?'MIC MUTED':(V.ptt?(V.pressed?'TRANSMITTING':'CAPSLOCK TO TALK'):'VOICE LIVE');dot.className=tx?'talk':'live';m.textContent=V.muted?'UNMUTE':'MUTE';r.textContent=V.radio?'RADIO ON':'RADIO';}
function attachAudio(call,id){safe(()=>{call.on('stream',stream=>{let a=V.audio.get(id);if(!a){a=document.createElement('audio');a.autoplay=true;a.playsInline=true;a.dataset.peer=id;document.body.appendChild(a);V.audio.set(id,a);}a.srcObject=stream;safe(()=>a.play());});call.on('close',()=>removeAudio(id));call.on('error',()=>removeAudio(id));});}
function removeAudio(id){const a=V.audio.get(id);if(!a)return;safe(()=>a.pause());safe(()=>a.srcObject=null);safe(()=>a.remove());V.audio.delete(id);}
function answerIncoming(call){safe(()=>{if(V.stream)call.answer(V.stream);else call.answer();attachAudio(call,call.peer);});}
function callPeer(id){if(!V.stream||!window.peer||!id)return;safe(()=>{const c=window.peer.call(id,V.stream,{metadata:{kind:'backrooms-voice'}});if(c)attachAudio(c,id);});}
function hookPeer(){const p=window.peer;if(!p||p===hookPeer.last||!p.on)return;hookPeer.last=p;safe(()=>p.on('call',answerIncoming));}
async function enable(){if(V.stream)return;if(!navigator.mediaDevices?.getUserMedia){V.lastError='Microphone APIs unavailable';refresh();return;}try{V.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});V.enabled=true;V.muted=true;for(const t of V.stream.getAudioTracks())t.enabled=false;hookPeer();connectCurrentPeers();refresh();safe(()=>showToast?.('VOICE READY • CAPSLOCK TO TALK',1800));}catch(e){V.lastError=e?.name||'Microphone denied';refresh();safe(()=>showToast?.('MICROPHONE NOT AVAILABLE',2200));}}
function setMuted(m){V.muted=!!m;if(V.stream)for(const t of V.stream.getAudioTracks())t.enabled=!V.muted;refresh();}function toggleMute(){if(!V.stream){enable();return;}setMuted(!V.muted);}function toggleRadio(){V.radio=!V.radio;refresh();safe(()=>showToast?.(V.radio?'RADIO LINK ENABLED':'RADIO LINK DISABLED',1200));}
function connectCurrentPeers(){hookPeer();safe(()=>{if(typeof connections!=='undefined')for(const c of connections.values())if(c?.open)callPeer(c.peer);});safe(()=>{if(typeof hostConnection!=='undefined'&&hostConnection?.open)callPeer(hostConnection.peer);});}
function bindConnection(c){if(!c||V.wired.has(c))return;V.wired.add(c);c.on('open',()=>{if(V.stream)callPeer(c.peer);});c.on('close',()=>removeAudio(c.peer));}
function remotePos(id){return safe(()=>{const r=typeof remotePlayers!=='undefined'?remotePlayers.get(id):null;return r?.position||r?.group?.position||r?.userData?.position||null;});}
function localPos(){return safe(()=>{const c=typeof controls!=='undefined'?controls:window.controls;return c?.getObject?.().position||null;});}
function updateSpatial(){const lp=localPos();if(!lp)return;const ray=new THREE.Raycaster();for(const [id,a] of V.audio){let vol=1;if(!V.radio){const rp=remotePos(id);if(rp){const d=lp.distanceTo(rp);vol=Math.max(0,1-d/34);const dir=new THREE.Vector3().subVectors(rp,lp).normalize();const wallHits=typeof walls!=='undefined'&&Array.isArray(walls)?ray.intersectObjects(walls,true):[];if(wallHits.length){const near=wallHits.find(x=>x.distance>0&&x.distance<d);if(near)vol*=.3;} }else vol=.7;}a.volume=Math.max(0,Math.min(1,vol));}}
function pump(){hookPeer();ui(typeof gameActive!=='undefined'&&gameActive);safe(()=>{if(typeof connections!=='undefined')for(const c of connections.values())bindConnection(c);});safe(()=>{if(typeof hostConnection!=='undefined')bindConnection(hostConnection);});if(typeof gameActive!=='undefined'&&gameActive&&V.stream&&V.enabled)connectCurrentPeers();const transmitting=V.stream&&V.enabled&&!V.muted&&(!V.ptt||V.pressed);if(V.stream)for(const t of V.stream.getAudioTracks())t.enabled=!!transmitting;updateSpatial();refresh();requestAnimationFrame(pump);}
function keys(){document.addEventListener('keydown',e=>{if(e.code==='CapsLock'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();V.pressed=true;refresh();}});document.addEventListener('keyup',e=>{if(e.code==='CapsLock'){V.pressed=false;refresh();}});window.addEventListener('blur',()=>{V.pressed=false;refresh();});}
function init(){css();dom();keys();pump();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.BackroomsVoice={enable,toggleMute,toggleRadio,setPushToTalk:on=>{V.ptt=!!on;refresh();},state:()=>({enabled:V.enabled,muted:V.muted,ptt:V.ptt,radio:V.radio,lastError:V.lastError})};
})();
